# Generated by Django 5.0.6 on 2024-06-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctorlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorphoto', models.ImageField(max_length=200, upload_to='')),
                ('doctorname', models.CharField(max_length=200)),
                ('doctoremail', models.CharField(max_length=200)),
                ('doctorqualification', models.CharField(max_length=200)),
                ('enterdutystarttime', models.CharField(max_length=200)),
                ('anysuggestion', models.CharField(max_length=200)),
            ],
        ),
    ]
